// Generated by gencpp from file beginner_tutorials/beginner_tutorials.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_BEGINNER_TUTORIALS_H
#define BEGINNER_TUTORIALS_MESSAGE_BEGINNER_TUTORIALS_H

#include <ros/service_traits.h>


#include <beginner_tutorials/beginner_tutorialsRequest.h>
#include <beginner_tutorials/beginner_tutorialsResponse.h>


namespace beginner_tutorials
{

struct beginner_tutorials
{

typedef beginner_tutorialsRequest Request;
typedef beginner_tutorialsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct beginner_tutorials
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::beginner_tutorials > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::beginner_tutorials::beginner_tutorials&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::beginner_tutorials > {
  static const char* value()
  {
    return "beginner_tutorials/beginner_tutorials";
  }

  static const char* value(const ::beginner_tutorials::beginner_tutorials&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::beginner_tutorialsRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::beginner_tutorials > 
template<>
struct MD5Sum< ::beginner_tutorials::beginner_tutorialsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::beginner_tutorials >::value();
  }
  static const char* value(const ::beginner_tutorials::beginner_tutorialsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::beginner_tutorialsRequest> should match 
// service_traits::DataType< ::beginner_tutorials::beginner_tutorials > 
template<>
struct DataType< ::beginner_tutorials::beginner_tutorialsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::beginner_tutorials >::value();
  }
  static const char* value(const ::beginner_tutorials::beginner_tutorialsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::beginner_tutorialsResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::beginner_tutorials > 
template<>
struct MD5Sum< ::beginner_tutorials::beginner_tutorialsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::beginner_tutorials >::value();
  }
  static const char* value(const ::beginner_tutorials::beginner_tutorialsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::beginner_tutorialsResponse> should match 
// service_traits::DataType< ::beginner_tutorials::beginner_tutorials > 
template<>
struct DataType< ::beginner_tutorials::beginner_tutorialsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::beginner_tutorials >::value();
  }
  static const char* value(const ::beginner_tutorials::beginner_tutorialsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_BEGINNER_TUTORIALS_H
